In [1]:
from Bio import Phylo
import pandas as pd
import bz2

In [33]:
abundances = pd.read_table('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/nw_profiles.tsv')
abundances.index = abundances['Unnamed: 0']
abundances = abundances.drop('Unnamed: 0',1)
keep = list()
for x in abundances.index.tolist():
    keep.append('t__' in x)
sgb_abundances = abundances.loc[keep]
sgb_abundances = sgb_abundances.transpose()
sgb_abundances = sgb_abundances.drop(sgb_abundances.loc[sgb_abundances.sum(axis=1) == 0].index.tolist())
sgb_abundances

/tmp/ipykernel_51971/3393769977.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  abundances = abundances.drop('Unnamed: 0',1)

Unnamed: 0,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_copri_clade_A|t__SGB1626,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminococcus|s__Ruminococcus_sp_NSJ_71|t__SGB4290,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Coprococcus|s__Coprococcus_eutactus|t__SGB5117,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__GGB3226|s__GGB3226_SGB4260|t__SGB4260,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminococcaceae_unclassified|s__Ruminococcaceae_unclassified_SGB15234|t__SGB15234,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidales_unclassified|g__Phocaeicola|s__Phocaeicola_vulgatus|t__SGB1814,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Rikenellaceae|g__Alistipes|s__Alistipes_putredinis|t__SGB2318,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Veillonellales|f__Veillonellaceae|g__Dialister|s__Dialister_invisus|t__SGB5825_group,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Faecalibacterium|s__Faecalibacterium_prausnitzii|t__SGB15332_group,k__Bacteria|p__Firmicutes|c__Bacilli|o__Bacilli_unclassified|f__Bacilli_unclassified|g__Bacilli_unclassified|s__Bacilli_unclassified_SGB6571|t__SGB6571,...,k__Bacteria|p__Proteobacteria|c__Betaproteobacteria|o__Burkholderiales|f__Alcaligenaceae|g__Kerstersia|s__Kerstersia_gyiorum|t__SGB13160,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium|s__Clostridium_mediterraneense|t__SGB21135,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae|g__GGB28645|s__GGB28645_SGB41267|t__SGB41267,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidales_unclassified|g__GGB27885|s__GGB27885_SGB40319|t__SGB40319,k__Archaea|p__Candidatus_Thermoplasmatota|c__Thermoplasmata|o__Methanomassiliicoccales|f__Methanomassiliicoccaceae|g__Methanomassiliicoccus|s__Methanomassiliicoccus_luminyensis|t__SGB33442,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Odoribacteraceae|g__GGB28250|s__GGB28250_SGB40793|t__SGB40793,k__Bacteria|p__Bacteroidetes|c__CFGB4425|o__OFGB4425|f__FGB4425|g__GGB27924|s__GGB27924_SGB40362|t__SGB40362,k__Bacteria|p__Actinobacteria|c__Actinobacteria|o__Propionibacteriales|f__Propionibacteriaceae|g__Propionibacteriaceae_unclassified|s__Propionibacteriaceae_bacterium_NML_150081|t__SGB15922,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidales_unclassified|g__GGB27883|s__GGB27883_SGB40317|t__SGB40317,k__Bacteria|p__Bacteroidetes|c__CFGB570|o__OFGB570|f__FGB570|g__GGB1201|s__GGB1201_SGB1566|t__SGB1566
MMRS62666492ST-27-0-0,11.54777,6.73408,5.34157,3.17368,2.98767,2.71605,2.62759,2.55274,2.30150,2.12654,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS51737257ST-27-0-0,0.00000,0.67540,0.00041,0.00000,0.00000,4.25769,0.78997,0.00000,1.33619,0.82690,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS38861560ST-27-0-0,0.00561,3.45553,1.53598,0.00000,0.70183,13.45227,2.19867,0.00000,0.57779,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS95674036ST-27-0-0,0.00000,0.00000,0.00000,0.00000,0.00000,18.39640,1.92548,0.95926,0.02935,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS67096717ST-27-0-0,0.00000,0.00133,0.00000,0.00000,0.00000,6.14089,2.10991,1.17805,1.09216,0.03785,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SID72242320_SF07,0.00000,0.00000,1.05172,0.00000,0.88860,5.90205,2.47706,0.07185,0.12916,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID30920067_SF07,24.37621,0.00000,0.94246,0.00000,0.00000,3.48781,3.01311,0.00000,0.78934,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID11486372_SF08,0.00000,0.00000,0.00000,0.00000,0.00000,0.01068,3.31002,0.00000,0.31211,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID16913125_SF05,0.00000,4.52322,0.00000,0.00000,2.07058,1.82037,2.29620,3.55566,4.12254,0.50509,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID16853657_SF05,0.00000,0.00000,0.00000,0.00000,0.00000,6.30323,0.00000,0.00000,0.72957,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
ab_thresh = 0.001
keep = list()
for x in abundances.index.tolist():
    keep.append('t__' in x)
sgb_prevalences = abundances.loc[keep]
sgb_prevalences = sgb_prevalences.drop(sgb_prevalences.loc[sgb_prevalences.sum(axis=1) == 0].index.tolist())
sgb_prevalences[sgb_prevalences >= ab_thresh] = 1
sgb_prevalences[sgb_prevalences < ab_thresh] = 0
sgb_prevalences

,MMRS62666492ST-27-0-0,MMRS51737257ST-27-0-0,MMRS38861560ST-27-0-0,MMRS95674036ST-27-0-0,MMRS67096717ST-27-0-0,MMRS84085284ST-27-0-0,MMRS51307502ST-27-0-0,MMRS17963147ST-27-0-0,MMRS39582183ST-27-0-0,MMRS35808664ST-27-0-0,...,SID15785561_SF07,SID19401504_SF05,SID20269046_SF08,SID50492523_SF07,SID10502288_SF08,SID72242320_SF07,SID30920067_SF07,SID11486372_SF08,SID16913125_SF05,SID16853657_SF05
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_copri_clade_A|t__SGB1626,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminococcus|s__Ruminococcus_sp_NSJ_71|t__SGB4290,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Coprococcus|s__Coprococcus_eutactus|t__SGB5117,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__GGB3226|s__GGB3226_SGB4260|t__SGB4260,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminococcaceae_unclassified|s__Ruminococcaceae_unclassified_SGB15234|t__SGB15234,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Odoribacteraceae|g__GGB28250|s__GGB28250_SGB40793|t__SGB40793,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Bacteria|p__Bacteroidetes|c__CFGB4425|o__OFGB4425|f__FGB4425|g__GGB27924|s__GGB27924_SGB40362|t__SGB40362,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Bacteria|p__Actinobacteria|c__Actinobacteria|o__Propionibacteriales|f__Propionibacteriaceae|g__Propionibacteriaceae_unclassified|s__Propionibacteriaceae_bacterium_NML_150081|t__SGB15922,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidales_unclassified|g__GGB27883|s__GGB27883_SGB40317|t__SGB40317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Bacteria|p__Bacteroidetes|c__CFGB570|o__OFGB570|f__FGB570|g__GGB1201|s__GGB1201_SGB1566|t__SGB1566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
to_keep = list()
for sgb in sgb_prevalences.index:
    to_keep.append(sgb.split('|')[-1].replace('t__SGB','').replace('_group',''))
len(to_keep)

4892

In [2]:
tree = Phylo.read("/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/mpa_v4beta_Jan21_SGB_tree.nwk", "newick")

In [60]:
to_remove = list()
for terminal in tree.get_terminals():
    if terminal.name not in to_keep:
        to_remove.append(terminal.name)
print(len(to_remove))
print(len(tree.get_terminals()))

22066
26931

In [61]:
for terminal in to_remove:
    tree.prune(target=terminal)
print(len(tree.get_terminals()))

4865

In [3]:
Phylo.write(tree, "/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/full_sgbs.newick", "newick")

1

In [71]:
fisher = pd.read_csv('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/nw_fisher_test.tsv', sep='\t')
fisher.index = [x.split('|')[-1].replace('t__SGB','').replace('_group','') for x in fisher['Unnamed: 0'].tolist()]
fisher = fisher.drop('Unnamed: 0',1)
fisher

/tmp/ipykernel_51971/1071378769.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  fisher = fisher.drop('Unnamed: 0',1)

,odds_ration,p-value,Westernized_prevalence,Non-Westernized_prevalence,direction,FDR
1626,0.014648,0.000000e+00,37.642722,82.537835,False,0.000000e+00
4290,0.040698,0.000000e+00,17.558213,44.470314,False,0.000000e+00
5117,0.027080,0.000000e+00,32.581138,47.438882,False,0.000000e+00
15234,0.023652,0.000000e+00,40.753394,60.302678,False,0.000000e+00
1814,0.036626,0.000000e+00,80.005394,56.635623,True,0.000000e+00
...,...,...,...,...,...,...
9209,0.479845,5.374540e-09,0.872067,22.409779,False,5.555704e-09
14905,0.347141,2.173146e-23,1.375528,27.066356,False,2.315785e-23
1673,0.474200,4.951833e-09,0.854086,21.420256,False,5.128352e-09
13999,0.286832,3.002790e-33,1.537355,23.923166,False,3.262874e-33
1701,0.586825,2.304539e-05,0.800144,26.600698,False,2.351396e-05

In [11]:
phylum = dict()
phylum2count = dict()
sgb2unk = dict()
with bz2.open('/shares/CIBIO-Storage/CM/scratch/databases/MetaRefSGB/releases/Jun23/SGB.Jun23.txt.bz2', 'rt') as read_file:
    for line in read_file:
        if line.startswith('SGB'):
            line = line.strip().split('\t')
            sgb2unk[line[1]]= line[7]
            phylum[line[1]] = line[9].split('|')[1].replace('p__','')
            if line[9].split('|')[1].replace('p__','') not in phylum2count:
                phylum2count[line[9].split('|')[1].replace('p__','')] = 0
            phylum2count[line[9].split('|')[1].replace('p__','')] += 1
        elif line.startswith('GGB'):
            break
phylum2count

{'Nanoarchaeota': 622,
 'Candidatus_Diapherotrites': 108,
 'Candidatus_Komeilibacteria': 832,
 'Firmicutes': 26674,
 'Proteobacteria': 31684,
 'Euryarchaeota': 1836,
 'Crenarchaeota': 281,
 'Spirochaetes': 1153,
 'Archaea_unclassified': 136,
 'Chloroflexi': 2647,
 'Bacteria_unclassified': 1802,
 'Candidatus_Saccharibacteria': 2357,
 'Bacteroidota': 14493,
 'Candidatus_Kryptonia': 287,
 'Candidatus_Micrarchaeota': 50,
 'Candidatus_Bathyarchaeota': 259,
 'Candidatus_Thermoplasmatota': 1097,
 'Planctomycetota': 1830,
 'Thaumarchaeota': 637,
 'Nitrospinae': 76,
 'Candidatus_Aenigmarchaeota': 49,
 'Candidatus_Korarchaeota': 17,
 'Candidatus_Roizmanbacteria': 199,
 'Actinobacteria': 13229,
 'Tenericutes': 838,
 'Verrucomicrobia': 1905,
 'Nitrospirae': 628,
 'Candidatus_Cloacimonetes': 88,
 'Cyanobacteria': 1425,
 'Balneolaeota': 139,
 'Gemmatimonadetes': 276,
 'Thermotogae': 106,
 'Acidobacteria': 2436,
 'Kiritimatiellaeota': 227,
 'Fibrobacteres': 199,
 'Armatimonadetes': 160,
 'Candidatus_Fervidibacteria': 18,
 'Candidatus_Parcubacteria': 704,
 'Candidatus_Omnitrophica': 427,
 'Candidatus_Gracilibacteria': 101,
 'Candidatus_Poribacteria': 79,
 'Candidatus_Falkowbacteria': 416,
 'Synergistetes': 180,
 'Calditrichaeota': 117,
 'Candidatus_Microgenomates': 85,
 'Lentisphaerae': 446,
 'Elusimicrobia': 266,
 'Chlamydiae': 266,
 'Candidatus_Melainabacteria': 562,
 'Candidatus_Margulisbacteria': 40,
 'Atribacterota': 50,
 'Ignavibacteriae': 287,
 'Fusobacteria': 334,
 'Candidatus_Absconditabacteria': 89,
 'Aquificae': 124,
 'Deferribacteres': 99,
 'Chlorobi': 56,
 'Dictyoglomi': 27,
 'Coprothermobacterota': 12,
 'Chrysiogenetes': 3,
 'Candidatus_Aminicenantes': 159,
 'candidate_division_NC10': 55,
 'Candidatus_Bipolaricaulota': 74,
 'Candidatus_Shapirobacteria': 34,
 'Rhodothermaeota': 36,
 'Deinococcus_Thermus': 201,
 'Caldiserica': 20,
 'Thermodesulfobacteria': 50,
 'Candidatus_Calescamantes': 6,
 'Candidatus_Eremiobacteraeota': 97,
 'Candidatus_Marinimicrobia': 484,
 'Abditibacteriota': 20,
 'Candidatus_Cryosericota': 19,
 'Candidatus_Hydrogenedentes': 55,
 'Candidatus_Nanohaloarchaeota': 2,
 'Candidatus_Latescibacteria': 6,
 'Candidatus_Aerophobetes': 24}

In [6]:
phylum2color = dict()
phylum2color['Firmicutes'] = '#b69fc9'
phylum2color['Euryarchaeota'] = '#afa9cf'
phylum2color['Actinobacteria'] = '#3c63a4'
phylum2color['Bacteroidota'] = '#528f28'
phylum2color['Proteobacteria'] = '#af1e21'
phylum2color['Spirochaetes'] = '#d27063'
phylum2color['Verrucomicrobia'] = '#fbffaa'
phylum2color['Tenericutes'] = '#e8b05b'
phylum2color['Fusobacteria'] = '#cbe6b9'
phylum2color['Candidatus_Melainabacteria'] = '#884a25'
phylum2color['Candidatus_Saccharibacteria'] = '#502984'
phylum2color['Synergistetes'] = '#a6c0d9'
phylum2color['Elusimicrobia'] = '#b3d960'
phylum2color['Candidatus_Thermoplasmatota'] = '#cccccc'

In [7]:
tree = Phylo.read('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/all_sgbs.newick', "newick")
with open('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/all_graphlan_metadata.tsv', 'w') as write_file:
    for terminal in tree.get_terminals():
        write_file.write(terminal.name+"\tclade_marker_edge_width\t0.2\n")
        if terminal.name in fisher.index.tolist():
            if fisher.loc[terminal.name]['direction'] == False:
                write_file.write(terminal.name+'\tring_color\t1\t#f1632a\n')
            elif fisher.loc[terminal.name]['direction'] == True:
                write_file.write(terminal.name+'\tring_color\t1\t#004b79\n')
        if phylum[terminal.name] in phylum2color:
            color = phylum2color[phylum[terminal.name]]
        else:
            color = '#000000'
        write_file.write(terminal.name+"\tclade_marker_color\t"+color+"\n")

In [98]:
tree = Phylo.read('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/all_sgbs.newick', "newick")
with open('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/all_graphlan_metadata_rev.tsv', 'w') as write_file:
    for terminal in tree.get_terminals():
        write_file.write(terminal.name+"\tclade_marker_edge_width\t0.2\n")
        if terminal.name in fisher.index.tolist():
            if fisher.loc[terminal.name]['direction'] == False:           
                write_file.write(terminal.name+"\tclade_marker_color\t#f1632a\n")
            elif fisher.loc[terminal.name]['direction'] == True:              
                write_file.write(terminal.name+"\tclade_marker_color\t#004b79\n")
        else:
            write_file.write(terminal.name+"\tclade_marker_size\t0\n")
        if phylum[terminal.name] in phylum2color:
            color = phylum2color[phylum[terminal.name]]
        else:
            color = '#000000'
        write_file.write(terminal.name+'\tring_color\t1\t'+color+'\n')

In [12]:
tree = Phylo.read('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/full_sgbs_new.newick', "newick")
with open('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/utils/full_graphlan_metadata_new.tsv', 'w') as write_file:
    for terminal in tree.get_terminals():
        write_file.write(terminal.name+"\tclade_marker_edge_width\t0.2\n")
        write_file.write(terminal.name+"\tclade_marker_size\t20\n")
        if phylum[terminal.name] in phylum2color:
            color = phylum2color[phylum[terminal.name]]
        else:
            color = '#000000'
        write_file.write(terminal.name+"\tclade_marker_color\t"+color+"\n")

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.

In [ ]:
good=[]
bad=[]

In [14]:
tree = Phylo.read('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/tests/chocophlansgb/PBCACA-001_BUFFER_H2O_DON14_T0.nwk', "newick")
with open('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/tests/chocophlansgb/PBCACA-001_BUFFER_H2O_DON14_T0_metadata.tsv', 'w') as write_file:
    for terminal in tree.get_terminals():
        write_file.write(terminal.name+"\tclade_marker_edge_width\t0.2\n")
        if sgb2unk[terminal.name] == 'uSGB':
            write_file.write(terminal.name+'\tring_color\t1\t#f1632a\n')
        else:
            write_file.write(terminal.name+'\tring_color\t1\t#004b79\n')

        
        if phylum[terminal.name] in phylum2color:
            color = phylum2color[phylum[terminal.name]]
        else:
            color = '#000000'
        write_file.write(terminal.name+"\tclade_marker_color\t"+color+"\n")

In [10]:
terminal.name

'10116'