In [1]:
import os, math, scipy, skbio, statistics
import numpy as np
import pandas as pd
from skbio.diversity import beta_diversity
from skbio.stats.ordination import pcoa
from skbio.stats.composition import clr
import seaborn as sns
import matplotlib as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy.stats import fisher_exact
from statsmodels.stats.multitest import fdrcorrection

/tmp/ipykernel_32680/3393769977.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  abundances = abundances.drop('Unnamed: 0',1)

Unnamed: 0,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_copri_clade_A|t__SGB1626,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminococcus|s__Ruminococcus_sp_NSJ_71|t__SGB4290,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Coprococcus|s__Coprococcus_eutactus|t__SGB5117,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__GGB3226|s__GGB3226_SGB4260|t__SGB4260,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminococcaceae_unclassified|s__Ruminococcaceae_unclassified_SGB15234|t__SGB15234,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidales_unclassified|g__Phocaeicola|s__Phocaeicola_vulgatus|t__SGB1814,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Rikenellaceae|g__Alistipes|s__Alistipes_putredinis|t__SGB2318,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Veillonellales|f__Veillonellaceae|g__Dialister|s__Dialister_invisus|t__SGB5825_group,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Faecalibacterium|s__Faecalibacterium_prausnitzii|t__SGB15332_group,k__Bacteria|p__Firmicutes|c__Bacilli|o__Bacilli_unclassified|f__Bacilli_unclassified|g__Bacilli_unclassified|s__Bacilli_unclassified_SGB6571|t__SGB6571,...,k__Bacteria|p__Proteobacteria|c__Betaproteobacteria|o__Burkholderiales|f__Alcaligenaceae|g__Kerstersia|s__Kerstersia_gyiorum|t__SGB13160,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Clostridiaceae|g__Clostridium|s__Clostridium_mediterraneense|t__SGB21135,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Eubacteriaceae|g__GGB28645|s__GGB28645_SGB41267|t__SGB41267,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidales_unclassified|g__GGB27885|s__GGB27885_SGB40319|t__SGB40319,k__Archaea|p__Candidatus_Thermoplasmatota|c__Thermoplasmata|o__Methanomassiliicoccales|f__Methanomassiliicoccaceae|g__Methanomassiliicoccus|s__Methanomassiliicoccus_luminyensis|t__SGB33442,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Odoribacteraceae|g__GGB28250|s__GGB28250_SGB40793|t__SGB40793,k__Bacteria|p__Bacteroidetes|c__CFGB4425|o__OFGB4425|f__FGB4425|g__GGB27924|s__GGB27924_SGB40362|t__SGB40362,k__Bacteria|p__Actinobacteria|c__Actinobacteria|o__Propionibacteriales|f__Propionibacteriaceae|g__Propionibacteriaceae_unclassified|s__Propionibacteriaceae_bacterium_NML_150081|t__SGB15922,k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidales_unclassified|g__GGB27883|s__GGB27883_SGB40317|t__SGB40317,k__Bacteria|p__Bacteroidetes|c__CFGB570|o__OFGB570|f__FGB570|g__GGB1201|s__GGB1201_SGB1566|t__SGB1566
MMRS62666492ST-27-0-0,11.54777,6.73408,5.34157,3.17368,2.98767,2.71605,2.62759,2.55274,2.30150,2.12654,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS51737257ST-27-0-0,0.00000,0.67540,0.00041,0.00000,0.00000,4.25769,0.78997,0.00000,1.33619,0.82690,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS38861560ST-27-0-0,0.00561,3.45553,1.53598,0.00000,0.70183,13.45227,2.19867,0.00000,0.57779,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS95674036ST-27-0-0,0.00000,0.00000,0.00000,0.00000,0.00000,18.39640,1.92548,0.95926,0.02935,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MMRS67096717ST-27-0-0,0.00000,0.00133,0.00000,0.00000,0.00000,6.14089,2.10991,1.17805,1.09216,0.03785,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SID72242320_SF07,0.00000,0.00000,1.05172,0.00000,0.88860,5.90205,2.47706,0.07185,0.12916,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID30920067_SF07,24.37621,0.00000,0.94246,0.00000,0.00000,3.48781,3.01311,0.00000,0.78934,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID11486372_SF08,0.00000,0.00000,0.00000,0.00000,0.00000,0.01068,3.31002,0.00000,0.31211,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID16913125_SF05,0.00000,4.52322,0.00000,0.00000,2.07058,1.82037,2.29620,3.55566,4.12254,0.50509,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SID16853657_SF05,0.00000,0.00000,0.00000,0.00000,0.00000,6.30323,0.00000,0.00000,0.72957,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
metadata = pd.read_csv('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/nw_metadata.tsv', sep='\t')
metadata

,study_name,sample_id,subject_id,body_site,antibiotics_current_use,study_condition,disease,age,age_category,gender,...,non_westernized,sequencing_platform,PMID,number_reads,number_bases,minimum_read_length,median_read_length,NCBI_accession,curator,DNA_extraction_kit
0,NielsenHB_2014,O2_UC49_0,O2_UC49,stool,NaN,control,healthy,22.0,adult,female,...,no,IlluminaHiSeq,24997787.0,60584637.0,4.099972e+09,30.0,70.0,ERR210493;ERR210492;ERR209641;ERR209640,Paolo_Manghi,NaN
1,NielsenHB_2014,O2_UC49_2,O2_UC49,stool,NaN,control,healthy,22.0,adult,female,...,no,IlluminaHiSeq,24997787.0,56508214.0,3.775477e+09,30.0,70.0,ERR210495;ERR210494;ERR209643;ERR209642,Paolo_Manghi,NaN
2,NielsenHB_2014,O2_UC50_0,O2_UC50,stool,NaN,control,healthy,24.0,adult,male,...,no,IlluminaHiSeq,24997787.0,65105855.0,4.392995e+09,30.0,71.0,ERR210497;ERR210496;ERR209645;ERR209644,Paolo_Manghi,NaN
3,NielsenHB_2014,O2_UC50_2,O2_UC50,stool,NaN,control,healthy,24.0,adult,male,...,no,IlluminaHiSeq,24997787.0,53260679.0,3.596382e+09,30.0,70.0,ERR210500;ERR209648,Paolo_Manghi,NaN
4,NielsenHB_2014,O2_UC51_0,O2_UC51,stool,NaN,control,healthy,32.0,adult,female,...,no,IlluminaHiSeq,24997787.0,57486896.0,3.923766e+09,30.0,72.0,ERR210502;ERR210501;ERR209650;ERR209649,Paolo_Manghi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12865,BorryM_2020,SAMEA6415059,SAMEA6415059,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12866,BorryM_2020,ERR3761407,ERR3761407,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12867,BorryM_2020,ERR3761411,ERR3761411,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12868,HaganRW_2019,Zape5,Zape5,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12869,HaganRW_2019,Zape28,Zape28,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
samples_with_profile = sgb_abundances.index.tolist()
samples_with_profile

['MMRS62666492ST-27-0-0',
 'MMRS51737257ST-27-0-0',
 'MMRS38861560ST-27-0-0',
 'MMRS95674036ST-27-0-0',
 'MMRS67096717ST-27-0-0',
 'MMRS84085284ST-27-0-0',
 'MMRS51307502ST-27-0-0',
 'MMRS17963147ST-27-0-0',
 'MMRS39582183ST-27-0-0',
 'MMRS35808664ST-27-0-0',
 'MMRS91297590ST-27-0-0',
 'MMRS95277876ST-27-0-0',
 'MMRS36405092ST-27-0-0',
 'MMRS93621581ST-27-0-0',
 'MMRS97307143ST-27-0-0',
 'MMRS85438660ST-27-0-0',
 'MMRS92546335ST-27-0-0',
 'MMRS33294861ST-27-0-0',
 'MMRS84159866ST-27-0-0',
 'MMRS92727331ST-27-0-0',
 'MMRS95479054ST-27-0-0',
 'MMRS21365932ST-27-0-0',
 'MMRS71238091ST-27-0-0',
 'MMRS34569532ST-27-0-0',
 'MMRS48639115ST-27-0-0',
 'MMRS81135225ST-27-0-0',
 'MMRS25211151ST-27-0-0',
 'MMRS38954404ST-27-0-0',
 'MMRS11664448ST-27-0-0',
 'MMRS39415781ST-27-0-0',
 'MMRS17603756ST-27-0-0',
 'MMRS42570301ST-27-0-0',
 'MMRS11288076ST-27-0-0',
 'MMRS85548821ST-27-0-0',
 'MMRS67690541ST-27-0-0',
 'MMRS29805707ST-27-0-0',
 'MMRS57276462ST-27-0-0',
 'MMRS65862658ST-27-0-0',
 'MMRS61683006ST-27-0-0',
 'MMRS94549160ST-27-0-0',
 'MMRS73787048ST-27-0-0',
 'MMRS88581325ST-27-0-0',
 'MMRS62192467ST-27-0-0',
 'MMRS20257302ST-27-0-0',
 'MMRS68630931ST-27-0-0',
 'MMRS87723283ST-27-0-0',
 'MMRS79893829ST-27-0-0',
 'MMRS57569834ST-27-0-0',
 'MMRS66868025ST-27-0-0',
 'MMRS11932626ST-27-0-0',
 'MMRS40913371ST-27-0-0',
 'MMRS32573774ST-27-0-0',
 'MMRS56137463ST-27-0-0',
 'MMRS64281551ST-27-0-0',
 'MMRS65742083ST-27-0-0',
 'MMRS81130264ST-27-0-0',
 'MMRS86168210ST-27-0-0',
 'MMRS54246132ST-27-0-0',
 'LILT_VF255_T016',
 'LILT_VF18_T016',
 'LILT_VF10_T016',
 'LILT_VF140_T016',
 'LILT_VF82_T016',
 'LILT_VF259_T016',
 'LILT_VF189_T016',
 'LILT_VF262_T016',
 'LILT_VF212_T016',
 'LILT_VF261_T016',
 'LILT_VF263_T016',
 'LILT_VF279_T016',
 'LILT_VF171_T016',
 'LILT_VF31_16',
 'GUI_0110107',
 'GUI_0210111',
 'GUI_0080320',
 'GUI_0140116',
 'GUI_0080201',
 'GUI_0210311',
 'GUI_0210315',
 'GUI_0080324',
 'GUI_0210119',
 'GUI_0080417',
 'GUI_0070123',
 'GUI_0210203',
 'GUI_0210124',
 'GUI_0140504',
 'GUI_0080308',
 'GUI_0140311',
 'GUI_0090501',
 'GUI_0210204',
 'GUI_0210304',
 'GUI_0210122',
 'GUI_0210117',
 'GUI_0080304',
 'GUI_0210405',
 'GUI_0080302',
 'GUI_0140118',
 'GUI_0140117',
 'GUI_0210303',
 'GUI_0210312',
 'GUI_0140403',
 'GUI_0080310',
 'GUI_0090401',
 'GUI_0080318',
 'GUI_0080403',
 'GUI_0210125',
 'GUI_0210302',
 'GUI_0140113',
 'GUI_0140308',
 'GUI_0080101',
 'GUI_0140115',
 'GUI_0020201',
 'GUI_0150117',
 'GUI_0210104',
 'GUI_0140305',
 'GUI_0090301',
 'GUI_0090304',
 'GUI_0090302',
 'GUI_2100107',
 'GUI_0140103',
 'GUI_0140101',
 'GUI_0140408',
 'GUI_0210317',
 'GUI_0210126',
 'GUI_0090502',
 'GUI_0140110',
 'GUI_0140506',
 'GUI_0090508',
 'GUI_0210121',
 'GUI_0140306',
 'GUI_0210107',
 'GUI_0130302',
 'GUI_0090512',
 'GUI_0080315',
 'GUI_2103211',
 'GUI_0140121',
 'GUI_0210109',
 'GUI_0140303',
 'GUI_0210411',
 'GUI_0140104',
 'GUI_0080307',
 'GUI_0210403',
 'GUI_0210306',
 'GUI_0210105',
 'GUI_0210202',
 'GUI_0140502',
 'GUI_0210127',
 'GUI_0090504',
 'GUI_0140411',
 'GUI_0140119',
 'GUI_0080103',
 'GUI_0090305',
 'GUI_0210309',
 'GUI_0090303',
 'GUI_0210406',
 'GUI_0090506',
 'GUI_0130103',
 'GUI_0210410',
 'GUI_0140108',
 'GUI_0140112',
 'GUI_0140404',
 'GUI_0210320',
 'GUI_0210301',
 'GUI_0080506',
 'GUI_0080312',
 'GUI_0080508',
 'GUI_0090511',
 'GUI_0210404',
 'GUI_0210101',
 'GUI_0140102',
 'GUI_0210318',
 'GUI_0140111',
 'GUI_0210205',
 'GUI_0210319',
 'GUI_0210402',
 'GUI_0080309',
 'GUI_0170201',
 'GUI_0080105',
 'GUI_0210118',
 'GUI_0210408',
 'GUI_0140122',
 'GUI_0140107',
 'GUI_0080311',
 'GUI_0210314',
 'GUI_0140307',
 'GUI_0210316',
 'CA_C10031MS2526FE_t0M15',
 'CA_C10026MS2440FE_t0M15',
 'CA_C10023IS2393FE_t2M15',
 'CA_C10019IS2352FE_t3M15',
 'CA_C10029MS2492FE_t0M15',
 'CA_C10020IS2336FE_t1M15',
 'CA_C10003IS2040FE_t3M15',
 'CA_C10005MS2062FE_t0M15',
 'CA_C10039IS2681FE_t3M16',
 'CA_C10052MS2904FE_t0M16',
 'CA_C10002IS2026FE_t3M15',
 'CA_C10049IS2854FE_t1M16',
 'CA_C10002IS2028FE_t4M15',
 'CA_C10026IS2451FE_t3M15',
 'CA_C10024IS2408FE_t1M15',
 'CA_C10042IS2739FE_t5M16',
 'CA_C10055IS2973FE_t4M16',
 'CA_C10023MS2386FE_t0M15',
 'CA_C10052IS2920FE_t5M16',
 'CA_C10005IS2069FE_t2M15',
 'CA_C10008IS2131FE_t5M16',
 'CA_C10039MS2669SA_t0M15',
 'CA_C10019IS2329FE_t4M15',
 'CA_C10003IS2042FE_t4M15',
 'CA_C10035IS2609FE_t3M16',
 'CA_C10024IS2419FE_t4M15',
 'CA_C10052IS2915FE_t3M16',
 'CA_C10055MS2958FE_t0M16',
 'CA_C10007IS2110FE_t3M15',
 'CA_C10034IS2584FE_t1M15',
 'CA_C10029IS2503FE_t3M15',
 'CA_C10035IS2913FE_t4M16',
 'CA_C10019IS2318FE_t1M15',
 'CA_C10024IS2411FE_t2M15',
 'CA_C10007IS2113FE_t5M16',
 'CA_C10043MS2742FE_t0M16',
 'CA_C10024IS2419FE_t5M16',
 'CA_C10001IS2006FE_t1M15',
 'CA_C10032IS2555FE_t3M15',
 'CA_C10042IS2739FE_t4M16',
 'CA_C10049IS2857FE_t2M16',
 'CA_C10032MS2544FE_t0M15',
 'CA_C10006IS2091FE_t3M15',
 'CA_C10007IS2102FE_t1M15',
 'CA_C10042MS2724FE_t0M16',
 'CA_C10055IS2962FE_t1M16',
 'CA_C10019IS2329FE_t5M16',
 'CA_C10001IS2009FE_t2M15',
 'CA_C10009IS2145FE_t3M16',
 'CA_C10052IS2908FE_t1M16',
 'CA_C10042IS2731FE_t2M16',
 'CA_C10020IS2345FE_t5M16',
 'CA_C10032IS2559FE_t5M16',
 'CA_C10006IS2087FE_t2M15',
 'CA_C10049IS2866FE_t5M16',
 'CA_C10023IS2401FE_t5M16',
 'CA_C10055IS2965FE_t2M16',
 'CA_C10031IS2541FE_t4M15',
 'CA_C10034IS2591FE_t3M15',
 'CA_C10006IS2095FE_t5M16',
 'CA_C10015IS2249FE_t2M15',
 'CA_C10006IS2084FE_t1M15',
 'CA_C10015IS2246FE_t1M15',
 'CA_C10049MS2850FE_t0M16',
 'CA_C10006IS2095FE_t4M15',
 'CA_C10029IS2496FE_t1M15',
 'CA_C10009IS2138FE_t1M15',
 'CA_C10055IS2969FE_t3M16',
 'CA_C10032IS2548FE_t1M15',
 'CA_C10020IS2339FE_t2M15',
 'CA_C10035IS2602FE_t1M15',
 'CA_C10009IS2141FE_t2M15',
 'CA_C10023IS2401FE_t4M16',
 'CA_C10031IS2537FE_t3M15',
 'CA_C10009IS2149FE_t4M15',
 'CA_C10031IS2530FE_t1M15',
 'CA_C10008IS2120FE_t1M15',
 'CA_C10007IS2114FE_t4M15',
 'CA_C10020IS2343FE_t3M15',
 'CA_C10005IS2066FE_t1M15',
 'CA_C10002IS2023FE_t2M15',
 'CA_C10023IS2397FE_t3M15',
 'CA_C10034IS2587FE_t2M15',
 'CA_C10005IS2077FE_t4M15',
 'CA_C10008IS2123FE_t2M15',
 'CA_C10003MS2030FE_t0M15',
 'CA_C10026IS2465FE_t4M16',
 'CA_C10007MS2098FE_t0M15',
 'CA_C10034IS2595FE_t4M15',
 'CA_C10032IS2551FE_t2M15',
 'CA_C10024IS2415FE_t3M15',
 'CA_C10049IS2861FE_t3M16',
 'CA_C10020IS2347FE_t4M15',
 'CA_C10029IS2499FE_t2M15',
 'CA_C10026IS2444FE_t1M15',
 'CA_C10035IS2605FE_t2M15',
 'CA_C10001IS2012FE_t3M15',
 'CA_C10019MS2314FE_t0M16',
 'CA_C10052IS2911FE_t2M16',
 'CA_C10023IS2390FE_t1M15',
 'CA_C10002MS2016FE_t0M15',
 'CA_C10008IS2127FE_t3M15',
 'CA_C10034MS2580FE_t0M15',
 'CA_C10015IS2235FE_t3M15',
 'CA_C10035MS2598FE_t0M15',
 'CA_C10039IS2677FE_t2M16',
 'CA_C10007IS2105FE_t2M15',
 'CA_C10015MS2242FE_t0M15',
 'CA_C10019IS2321FE_t2M15',
 'CA_C10026IS2449FE_t2M15',
 'CA_C10009IS2149FE_t5M16',
 'CA_C10043IS2749FE_t2M16',
 'CA_C10031IS2541FE_t5M16',
 'CA_C10032IS2559FE_t4M15',
 'CA_C10042IS2735FE_t3M16',
 'CA_C10009MS2134FE_t0M15',
 'CA_C10049IS2866FE_t4M16',
 'CA_C10020MS2332FE_t0M15',
 'CA_C10039MS2670FE_t0M16',
 'V1_C118',
 'V3_C119',
 'V2_C114',
 'V2_C111',
 'V3_C116',
 'M_C109',
 'V2_C117',
 'M_C115',
 'V1_C113',
 'M_C120',
 'V3_C114',
 'V2_C100',
 'M_C114',
 'V2_C120',
 'V2_C116',
 'V2_C118',
 'M_C105',
 'V3_C106',
 'V3_C113',
 'V3_C105',
 'V3_C112',
 'V2_C112',
 'V2_C101',
 'V3_C118',
 'V2_C106',
 'V3_C101',
 'V3_C117',
 'V2_C109',
 'V3_C100',
 'V3_C111',
 'V3_C115',
 'V2_C110',
 'V1_C110',
 'M_C100',
 'V3_C120',
 'M_C123',
 'V2_C115',
 'V1_C106',
 'V1_C120',
 'M_C111',
 'V1_C109',
 'M_C106',
 'M_C101',
 'M_C119',
 'V1_C101',
 'V1_C111',
 'M_C110',
 'V2_C119',
 'M_C117',
 'V3_C110',
 'V2_C105',
 'M_C118',
 'CHN_3E2',
 'CHN_26G3',
 'CHN_4E2',
 'CHN_18D2',
 'CHN_11E2',
 'CHN_2D3',
 'CHN_21D2',
 'CHN_24G2',
 'CHN_26G2',
 'CHN_12D2',
 'CHN_5D2',
 'CHN_1G2',
 'CHN_4E3',
 'CHN_7F2',
 'CHN_6E2',
 'CHN_8E2',
 'CHN_18E2',
 'CHN_11E3',
 'CHN_2D2',
 'CHN_19G2',
 'CHN_17D2',
 'CHN_21D3',
 'CHN_1E2',
 'CHN_1G3',
 'CHN_7E3',
 'CHN_8E3',
 'CHN_12D3',
 'CHN_7E2',
 'P10E0',
 'P23C0',
 'P15E0',
 'P6C90',
 'P8C90',
 'P3E0',
 'P7C90',
 'P6C0',
 'P25C90',
 'P6C7',
 'P11E0',
 'P23C7',
 'P38C90',
 'P4E0',
 'P13E0',
 'P7C0',
 'P8C7',
 'P1E0',
 'P8C0',
 'P17E0',
 'P12E0',
 'P21E0',
 'P25C7',
 'P20E0',
 'P23C90',
 'P22E0',
 'P38C7',
 'P19E0',
 'P25C0',
 'P5E0',
 'P18E0',
 'P7C7',
 'P38C0',
 'P9E0',
 'P14E0',
 'P2E0',
 'GupDM_HCP',
 'GupDM_HP',
 'GupDM_HCT',
 'GupDM_HCQ',
 'GupDM_HAJ',
 'GupDM_HCV',
 'GupDM_HCM',
 'GupDM_HCN',
 'GupDM_HAT',
 'GupDM_HDB',
 'GupDM_HCY',
 'GupDM_HCU',
 'GupDM_HCS',
 'GupDM_HR',
 'GupDM_HCO',
 'GupDM_HCL',
 'GupDM_HAK',
 'GupDM_HAM',
 'GupDM_HDF',
 'GupDM_HAI',
 'GupDM_HAR',
 'GupDM_HAN',
 'GupDM_HCR',
 'GupDM_HAL',
 'GupDM_HS',
 'GupDM_HAO',
 'GupDM_HAG',
 'GupDM_HAP',
 'GupDM_HAH',
 'GupDM_HBR',
 '2180a_merged',
 '2181a_100',
 '2179a_merged',
 'HMP2_J43814_M_ST_T0_B0_0120_ZYLJ7R7-03_C93B2ANXX',
 'HMP2_J00884_M_ST_T0_B0_0120_ZM7JY3G-04_C8GAAANXX',
 'HMP2_J00896_M_ST_T0_B0_0120_ZLZQMEV-01X_HA986ADXX',
 'HMP2_J00879_M_ST_T0_B0_0120_ZMBH10Z-01_AC9387ANXX',
 'HMP2_J00836_M_ST_T0_B0_0120_ZLZQMEV-03_HA986ADXX',
 'HMP2_J00880_M_ST_T0_B0_0120_ZMBH10Z-02_HA986ADXX',
 'HMP2_J00891_M_ST_T0_B0_0120_ZJTKAE3-01_HA986ADXX',
 'HMP2_J09104_M_ST_T0_B0_0120_ZM7JY3G-05_H7FHFBGXX_S36',
 'HMP2_J09105_M_ST_T0_B0_0120_ZM7JY3G-07_H7FHFBGXX_S37',
 'HMP2_J00881_M_ST_T0_B0_0120_ZMBH10Z-03_HA986ADXX',
 'HMP2_J08169_M_ST_T0_B0_0120_ZVNCGHM-6013_HCG2MBGXX_S22',
 'HMP2_J00893_M_ST_T0_B0_0120_ZJTKAE3-04_HA986ADXX',
 'HMP2_J08171_M_ST_T0_B0_0120_ZVNCGHM-6015_HCG2MBGXX_S24',
 'HMP2_J00879_M_ST_T0_B0_0120_ZMBH10Z-01_HA986ADXX',
 'HMP2_J09104_M_ST_T0_B0_0120_ZM7JY3G-05_C8GAAANXX',
 'HMP2_J43815_M_ST_T0_B0_0120_ZYLJ7R7-06_C93B2ANXX',
 'HMP2_J08172_M_ST_T0_B0_0120_ZVNCGHM-6016_HCG2MBGXX_S25',
 'HMP2_J00892_M_ST_T0_B0_0120_ZJTKAE3-02_HA986ADXX',
 'HMP2_J43813_M_ST_T0_B0_0120_ZYLJ7R7-02_C93B2ANXX',
 'HMP2_J00881_M_ST_T0_B0_0120_ZMBH10Z-03_C8GAAANXX',
 'HMP2_J00891_M_ST_T0_B0_0120_ZJTKAE3-01_C8GAAANXX',
 'HMP2_J00883_M_ST_T0_B0_0120_ZM7JY3G-02_HA986ADXX',
 'HMP2_J08170_M_ST_T0_B0_0120_ZVNCGHM-6014_HCG2MBGXX_S23',
 'HMP2_J15246_M_ST_T0_B0_0120_ZVGW5FI-02_GES15-03641',
 'HMP2_J08167_M_ST_T0_B0_0120_ZVNCGHM-02_HCG2MBGXX_S20',
 'HMP2_J15245_M_ST_T0_B0_0120_ZVGW5FI-01_BHLVVGADXX',
 'HMP2_J16531_M_ST_T0_B0_0120_ZVGW5FI-03_HK3LNBGXX_S2',
 'HMP2_J09105_M_ST_T0_B0_0120_ZM7JY3G-07_C8GAAANXX',
 'HMP2_J00882_M_ST_T0_B0_0120_ZM7JY3G-01_HA986ADXX',
 'HMP2_J15245_M_ST_T0_B0_0120_ZVGW5FI-01_GES15-03640',
 'HMP2_J05409_M_ST_T0_B0_0120_ZMBH10Z-04_C8GAAANXX',
 'HMP2_J15246_M_ST_T0_B0_0120_ZVGW5FI-02_BHLVVGADXX',
 'HMP2_J00879_M_ST_T0_B0_0120_ZMBH10Z-01_C8GAAANXX',
 'HMP2_J43812_M_ST_T0_B0_0120_ZYLJ7R7-01_C93B2ANXX',
 'HMP2_J00884_M_ST_T0_B0_0120_ZM7JY3G-04_HA986ADXX',
 'HMP2_J35165_M_ST_T0_B0_0120_ZMBH10Z-04_HBB8WADXX',
 'HMP2_J00880_M_ST_T0_B0_0120_ZMBH10Z-02_AC9387ANXX',
 'HMP2_J08168_M_ST_T0_B0_0120_ZVNCGHM-6012_HCG2MBGXX_S21',
 'HMP2_J00835_M_ST_T0_B0_0120_ZLZQMEV-01_HA986ADXX',
 'HMP2_J00880_M_ST_T0_B0_0120_ZMBH10Z-02_C8GAAANXX',
 'MG100166',
 'MG100179',
 'MG100162',
 'MG100161',
 'MG100168',
 'MG100160',
 'MG100156',
 'MG100177',
 'MG100171',
 'MG100159',
 'MG100167',
 'MG100157',
 'MG100163',
 'MG100180',
 'MG100178',
 'MG100170',
 'MG100174',
 'MG100164',
 'MG100153',
 'MG100154',
 'MG100155',
 'MG100169',
 'MG100176',
 'MG100172',
 'MG100158',
 'MG100175',
 'MG100165',
 'MG100173',
 'CM.432_WGS',
 'CM.364_WGS',
 'CM.528_WGS',
 'CM.530_WGS',
 'CM.16_WGS',
 'CM.490_WGS',
 'CM.553_WGS',
 'CM.574_WGS',
 'CM.536_WGS',
 'CM.275_WGS',
 'CM.347_WGS',
 'CM.340_WGS',
 'CM.443_WGS',
 'CM.278_WGS',
 'CM.310_WGS',
 'CM.373_WGS',
 'CM.199_WGS',
 'CM.345_WGS',
 'CM.283_WGS',
 'CM.412_WGS',
 'CM.178_WGS',
 'CM.339_WGS',
 'CM.520_WGS',
 'CM.67_WGS',
 'CM.413_WGS',
 'CM.228_WGS',
 'CM.409_WGS',
 'CM.514_WGS',
 'CM.343_WGS',
 'CM.361_WGS',
 'CM.418_WGS',
 'CM.29_WGS',
 'CM.316_WGS',
 'CM.289_WGS',
 'CM.342_WGS',
 'CM.164_WGS',
 'CM.378_WGS',
 'CM.291_WGS',
 'CM.317_WGS',
 'CM.358_WGS',
 'CM.24_WGS',
 'CM.512_WGS',
 'CM.454_WGS',
 'CM.408_WGS',
 'CM.437_WGS',
 'CM.328_WGS',
 'CM.395_WGS',
 'CM.375_WGS',
 'CM.285_WGS',
 'CM.532_WGS',
 'CM.308_WGS',
 'CM.555_WGS',
 'CM.376_WGS',
 'CM.369_WGS',
 'CM.389_WGS',
 'CM.580_WGS',
 'CM.367_WGS',
 'CM.397_WGS',
 'CM.438_WGS',
 'CM.525_WGS',
 'CM.177_WGS',
 'CM.370_WGS',
 'CM.511_WGS',
 'CM.147_WGS',
 'CM.162_WGS',
 'CM.403_WGS',
 'CM.486_WGS',
 'CM.466_WGS',
 'CM.79_WGS',
 'CM.439_WGS',
 'CM.146_WGS',
 'CM.392_WGS',
 'CM.208_WGS',
 'CM.284_WGS',
 'CM.206_WGS',
 'CM.382_WGS',
 'CM.294_WGS',
 'CM.152_WGS',
 'CM.47_WGS',
 'CM.366_WGS',
 'CM.335_WGS',
 'CM.402_WGS',
 'CM.445_WGS',
 'CM.425_WGS',
 'CM.82_WGS',
 'CM.129_WGS',
 'LD-Run2-12',
 'LD-Run2-20',
 'LD-Run2-19',
 'LD-Run2-36',
 'LD-Run2-29',
 'LD-Run2-24',
 'LD-Run2-11',
 'LD-Run2-13',
 'LD-Run2-37',
 'SID08D_257',
 'SID09C_517',
 'SID090101',
 'SID080101',
 'SID080301',
 'SID08J_078',
 'SID08B_044',
 'SID01G_005',
 'SID010302',
 'SID210102',
 'SID01A_006',
 'SID02B_552',
 'SID250502',
 'SID060301',
 'SID040301',
 'SID01B_221',
 'SID08D_079',
 'SID040104',
 'SID03C_000',
 'SID140104',
 'SID210401',
 'SID03B_000',
 'SID060102',
 'SID060401',
 'SID250102',
 'SID030702',
 'SID020301',
 'SID140201',
 'SID08K_237',
 'SID020102',
 'SID020202',
 'SID09A_515',
 'SID240304',
 'SID04B_564',
 'SID210402',
 'SID08E_000',
 'SID240301',
 'SID01H_202',
 'SID08K_032',
 'SID140304',
 'SID140302',
 'SID030301',
 'SID01C_235',
 'SID100404',
 'SID01E_015',
 'SID240202',
 'SID060402',
 'SID08E_041',
 'SID040204',
 'SID05A_000',
 'SID020302',
 'SID210302',
 'SID100204',
 'SID01D_570',
 'SID100201',
 'SID09B_516',
 'SID100402',
 'SID190104',
 'SID100304',
 'SID08H_008',
 'SID140102',
 'SID05C_000',
 'SID010304',
 'SID040202',
 'SID030102',
 'SID010102',
 'SID250101',
 'SID080104',
 'SID060202',
 'SID080304',
 'SID030601',
 'SID09D_518',
 'SID01D_190',
 'SID08K_560',
 'SID01C_566',
 'SID03F_000',
 'SID060502',
 'SID03E_000',
 'SID210101',
 'SID250501',
 'SID010104',
 'SID240102',
 'SID250702',
 'SID010101',
 'SID07E_559',
 'SID210201',
 'SID240101',
 'SID030604',
 'SID240402',
 'SID010204',
 'SID030204',
 'SID060302',
 'SID04C_565',
 'SID020204',
 'SID100302',
 'SID030602',
 'SID01F_573',
 'SID01I_012',
 'SID01E_000',
 'SID04E_563',
 'SID210204',
 'SID010401',
 'SID030704',
 'SID240401',
 'SID100202',
 'SID210404',
 'SID020304',
 'SID01F_239',
 'SID01A_000',
 'SID090102',
 'SID030502',
 'SID02C_553',
 'SID08A_000',
 'SID010301',
 'SID01I_569',
 'SID210304',
 'SID01A_220',
 'SID030101',
 'SID08E_160',
 'SID240201',
 'SID040303',
 'SID08G_000',
 'SID01G_234',
 'SID04D_562',
 'SID01H_011',
 'SID01G_000',
 'SID210301',
 'SID030701',
 'SID030201',
 'SID01B_007',
 'SID240302',
 'SID140101',
 'SID07A_558',
 'SID05D_000',
 'SID010201',
 'SID060601',
 'SID01E_191',
 'SID08G_023',
 'SID08I_545',
 'SID250301',
 'SID010404',
 'SID07D_542',
 'SID250704',
 'SID060602',
 'SID08F_000',
 'SID08H_000',
 'SID040101',
 'SID060101',
 'SID03D_000',
 'SID08F_040',
 'SID03G_000',
 'SID080302',
 'SID040203',
 'SID010202',
 'SID01D_013',
 'SID09E_519',
 'SID040304',
 'SID100301',
 'SID020104',
 'SID040201',
 'SID250701',
 'SID060201',
 'SID03A_000',
 'SID01J_173',
 'SID07C_541',
 'SID08A_022',
 'SID08I_170',
 'SID250104',
 'SID020201',
 'SID140202',
 'SID08A_236',
 'SID030202',
 'SID080102',
 'SID210104',
 'SID08I_009',
 'SID090201',
 'SID08C_021',
 'SID010402',
 'SID190101',
 'SID02A_561',
 'SID140301',
 'SID01H_568',
 'SID030504',
 'SID240104',
 'SID01J_010',
 'SID020101',
 'SID01B_000',
 'SID100401',
 'SID030104',
 'SID05B_000',
 'SID08D_572',
 'SRR8731958',
 'SRR8731955',
 'SRR8731957',
 'S137',
 'S614',
 'S146',
 'S155',
 'S288',
 'S655',
 'S194',
 'S53',
 'S424',
 'S456',
 'S77',
 'S365',
 'S264',
 'S268',
 'S231',
 'S88',
 'S628',
 'S193',
 'S141',
 'S127',
 'S381',
 'S643',
 'S195',
 'S58',
 'S225',
 'S92',
 'S153',
 'S584',
 'S463',
 'S224',
 'S451',
 'S269',
 'S118',
 'S198',
 'S80',
 'S121',
 'S187',
 'S126',
 'S617',
 'S143',
 'S479',
 'S618',
 'S59',
 'MV_FEM5_t1Q14',
 'MV_FEI5_t2Q14',
 'MV_FEM5_t2Q14',
 'MV_FEM2_t1Q14',
 'MV_FEI2_t1Q14',
 'MV_FEI1_t1Q14',
 'MV_FEI3_t1Q14',
 'MV_FEM4_t2Q15',
 'MV_FEM5_t3Q15',
 'MV_FEI5_t1Q14',
 'MV_FEM1_t1Q14',
 'MV_FEI4_t1Q14',
 'MV_FEM4_t1Q14',
 'MV_FEI4_t2Q15',
 'MV_FEM3_t1Q14',
 'MV_FEI5_t3Q15',
 'YSZC12003_35740',
 'YSZC12003_37255',
 'YSZC12003_37207R1',
 'YSZC12003_37175',
 'YSZC12003_37583',
 'YSZC12003_36158',
 'YSZC12003_36244',
 'YSZC12003_35703',
 'YSZC12003_37135',
 'YSZC12003_36674',
 'YSZC12003_37337',
 'YSZC12003_36666',
 'YSZC12003_36006',
 'YSZC12003_36389',
 'YSZC12003_36696',
 'YSZC12003_37304R1',
 'YSZC12003_37287',
 'YSZC12003_37830',
 'YSZC12003_37331',
 'YSZC12003_37182R1',
 'YSZC12003_35578',
 'YSZC12003_36474',
 'YSZC12003_35516',
 'YSZC12003_35990',
 'YSZC12003_37105',
 'YSZC12003_36588',
 'YSZC12003_37269',
 'YSZC12003_35561',
 'YSZC12003_35390',
 'YSZC12003_37399',
 'YSZC12003_37308R1',
 'YSZC12003_36522',
 'YSZC12003_37201',
 'YSZC12003_36051',
 'YSZC12003_37202R1',
 'YSZC12003_35698',
 'YSZC12003_36117',
 'YSZC12003_37544',
 'YSZC12003_35708',
 'YSZC12003_36012',
 'YSZC12003_37197R1',
 'YSZC12003_37176',
 'YSZC12003_37134',
 'YSZC12003_37271R1',
 'YSZC12003_37305R1',
 'YSZC12003_37254',
 'YSZC12003_37126',
 'YSZC12003_35658',
 'YSZC12003_37264',
 'YSZC12003_37297R1',
 'YSZC12003_37223',
 'YSZC12003_37191R1',
 'YSZC12003_37584',
 'YSZC12003_37349',
 'YSZC12003_36703',
 'YSZC12003_36118',
 'YSZC12003_36698',
 'YSZC12003_36454',
 'YSZC12003_36116',
 'YSZC12003_37296R1',
 'YSZC12003_37543',
 'YSZC12003_35365',
 'YSZC12003_37317',
 'YSZC12003_36534',
 'YSZC12003_35549',
 'YSZC12003_37101',
 'YSZC12003_36697',
 'YSZC12003_35577',
 'YSZC12003_35388',
 'YSZC12003_37298R1',
 'YSZC12003_36525',
 'YSZC12003_35564',
 'YSZC12003_37196',
 'YSZC12003_35707',
 'YSZC12003_37210',
 'YSZC12003_36439',
 'YSZC12003_37195',
 'YSZC12003_36795',
 'YSZC12003_35583',
 'YSZC12003_37353',
 'YSZC12003_36000',
 'YSZC12003_35979',
 'YSZC12003_35734',
 'YSZC12003_35739',
 'YSZC12003_35520',
 'YSZC12003_37293',
 'YSZC12003_37877',
 'YSZC12003_36019',
 'YSZC12003_35392',
 'YSZC12003_35733',
 'YSZC12003_37265R1',
 'YSZC12003_36981',
 'YSZC12003_35629',
 'YSZC12003_35562',
 'YSZC12003_35742',
 'YSZC12003_35989',
 'YSZC12003_37753',
 'YSZC12003_36453',
 'YSZC12003_36008',
 'YSZC12003_35505',
 'YSZC12003_37648',
 'YSZC12003_37299R1',
 'YSZC12003_36049',
 'YSZC12003_37133',
 'YSZC12003_36212',
 'YSZC12003_37138',
 'YSZC12003_37652',
 'YSZC12003_35665',
 'YSZC12003_35391',
 'YSZC12003_37651',
 'YSZC12003_35366',
 'YSZC12003_35666',
 'YSZC12003_36667',
 'YSZC12003_37181R1',
 'YSZC12003_36587',
 'YSZC12003_37878',
 'YSZC12003_37179',
 'YSZC12003_37292',
 'YSZC12003_35741',
 'YSZC12003_36034',
 'YSZC12003_37173',
 'YSZC12003_35512',
 'YSZC12003_36157',
 'YSZC12003_37268R1',
 'YSZC12003_37286',
 'YSZC12003_35980',
 'YSZC12003_35563',
 'YSZC12003_36020',
 'YSZC12003_37394',
 'YSZC12003_35723',
 ...]

In [10]:
filtered_metadata = metadata.loc[metadata['sample_id'].isin(samples_with_profile)]
filtered_metadata

,study_name,sample_id,subject_id,body_site,antibiotics_current_use,study_condition,disease,age,age_category,gender,...,non_westernized,sequencing_platform,PMID,number_reads,number_bases,minimum_read_length,median_read_length,NCBI_accession,curator,DNA_extraction_kit
0,NielsenHB_2014,O2_UC49_0,O2_UC49,stool,NaN,control,healthy,22.0,adult,female,...,no,IlluminaHiSeq,24997787.0,60584637.0,4.099972e+09,30.0,70.0,ERR210493;ERR210492;ERR209641;ERR209640,Paolo_Manghi,NaN
1,NielsenHB_2014,O2_UC49_2,O2_UC49,stool,NaN,control,healthy,22.0,adult,female,...,no,IlluminaHiSeq,24997787.0,56508214.0,3.775477e+09,30.0,70.0,ERR210495;ERR210494;ERR209643;ERR209642,Paolo_Manghi,NaN
2,NielsenHB_2014,O2_UC50_0,O2_UC50,stool,NaN,control,healthy,24.0,adult,male,...,no,IlluminaHiSeq,24997787.0,65105855.0,4.392995e+09,30.0,71.0,ERR210497;ERR210496;ERR209645;ERR209644,Paolo_Manghi,NaN
3,NielsenHB_2014,O2_UC50_2,O2_UC50,stool,NaN,control,healthy,24.0,adult,male,...,no,IlluminaHiSeq,24997787.0,53260679.0,3.596382e+09,30.0,70.0,ERR210500;ERR209648,Paolo_Manghi,NaN
4,NielsenHB_2014,O2_UC51_0,O2_UC51,stool,NaN,control,healthy,32.0,adult,female,...,no,IlluminaHiSeq,24997787.0,57486896.0,3.923766e+09,30.0,72.0,ERR210502;ERR210501;ERR209650;ERR209649,Paolo_Manghi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12865,BorryM_2020,SAMEA6415059,SAMEA6415059,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12866,BorryM_2020,ERR3761407,ERR3761407,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12867,BorryM_2020,ERR3761411,ERR3761411,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12868,HaganRW_2019,Zape5,Zape5,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12869,HaganRW_2019,Zape28,Zape28,stool,NaN,control,healthy,NaN,NaN,NaN,...,ancient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
for row in filtered_metadata.index:
    sample_id = filtered_metadata.loc[row]['sample_id']
    study_name = filtered_metadata.loc[row]['study_name']
    if not os.path.exists('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/sample2markers/{}'.format(study_name)):
        os.mkdir('/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/sample2markers/{}'.format(study_name))
    org = '/shares/CIBIO-Storage/CM/scratch/data/meta/{}/strainphlan-4beta_vJan21_CHOCOPhlAnSGB_202103/{}/{}.pkl'.format(study_name, sample_id, sample_id)
    dest = '/shares/CIBIO-Storage/CM/scratch/users/aitor.blancomiguez/analyses/nw_metanalysis/sample2markers/{}/{}.pkl'.format(study_name, sample_id)
    if os.path.exists(org):
        os.symlink(org, dest)
    else:
        print('Missing {}'.format(org))